### ISSUE TITLE
Use flat renderer

### ISSUE THREAD

**Issue by colinodell** [mnapoli/IsItMaintained#19]
![Flat](https://img.shields.io/badge/style-flat-green.svg?style=flat) badges seem to be more popular than ![plastic](https://img.shields.io/badge/style-plastic-green.svg?style=plastic) ones these days.  [badges/poser](https://github.com/badges/poser) supports the flat types using the [SvgFlatRenderer](https://github.com/badges/poser/blob/master/src/Render/SvgFlatRender.php).  Would it be possible to either replace the the [SvgRenderer](https://github.com/badges/poser/blob/master/src/Render/SvgRender.php) (which uses the older "plastic" format) or at least expose the flat format as an option?

**Comment by mnapoli** [comment]
:+1: I too prefer the flat style. I'm currently on holidays with not much time on my hands, if you have time for a pull request I would gladly merge it ;)

**Comment by mnapoli** [comment]
This was closed in #20 ;)
